### ISSUE TITLE
Remove snkmail.com

### ISSUE THREAD

**Issue by cantelope** [FGRibreau/mailchecker#108]
Please remove snkmail.com.  Although it started out as a disposable email service (sneakemail.com), snkmail.com is a paid-subscription service for generating long-lived unique email addresses for different purposes. 

Emails to the generated address is forwarded to the subscriber with the email tagged so that he knows which email it was sent to, and with the From address altered so that replies go back via snkmail servers and to the original sender.  So this is really a service for identifying spam from websites, and not for generating disposable emails.

**Comment by FGRibreau** [comment]
Closed because nobody else asked for it, I'm sorry
