### ISSUE TITLE
Invalid License for rust crate

### ISSUE THREAD

**Issue by YetAnotherMinion** [FGRibreau/mailchecker#125]
The `fast_chemail` library is licensed under the Mozilla Public License 2.0, which is a copyleft license. MPL 2.0 code cannot be used under a MIT or Apache License, because MPL 2.0 is more restrictive.

**Comment by FGRibreau** [comment]
We will have to change fast_chemail for something else then :)

**Comment by YetAnotherMinion** [comment]
Looks like https://crates.io/crates/publicsuffix has a simplistic and opinionated email validator.

**Comment by FGRibreau** [comment]
Closed due to inactivity
