### ISSUE TITLE
Please consider uploading Python version to pypi package index

### ISSUE THREAD

**Issue by jbzdak** [FGRibreau/mailchecker#127]
I know that dropping implementation in my git repository is easy enough, but keeping it up to date requires me to keep separate workflow than the rest of my dependencies (that are downloaded from pip). 

If you need any help with implementing I'd be happy to help.

**Comment by FGRibreau** [comment]
Hello @jbzdak :)

Could you please send a PR for this ?

**Comment by jbzdak** [comment]
Please see: https://github.com/FGRibreau/mailchecker/pull/133 

This adds setup.py script, to actually upload package you'll need to : 

1. Get a https://pypi.org/ account 
2. Ping me so I'll give you ownership of the package :)
3. Update version in setup.py 
4. ``cd platform python && python setup.py sdist upload`` 

I can automate steps 3 and 4 but I'll need some guidance ;) on where you want this automatisation in in this codebase.

**Comment by FGRibreau** [comment]
@jbzdak my id is `FGRibreau` :)

For automating the release, I run `npm run release-cross` that runs:
- `npm publish` release nodejs package
- `npm run publish-gem` for ruby 
- `npm run publish-cargo` for rust

(php composer is automatic)

So you might want to add a `publish-python3` line in package.json :)

**Comment by jbzdak** [comment]
Just a ping: I'll try to find some time this weekend ;)

**Comment by jbzdak** [comment]
@FGRibreau 

Right now you should be able to upload to python repository automatically. 

Also, I have added you to brand-new "mailchecker" package on pypi. 

Caveeats: 

* This assumes that you have *some* python installed locally (not really any specific version, any non archaic would do). If this is a problem I can dockerize it --- but then we'd have to pass credentials to upload function somehow (which is not elegant --- but doable). 
* When testing you'll need to issue new minor version as you can't override software versions in pypi.

**Comment by FGRibreau** [comment]
Done! Released in v3.2.2, thanks a lot!
