### ISSUE TITLE
add mail

### ISSUE THREAD

**Issue by techinnov-974** [FGRibreau/mailchecker#142]
Hello look the website:

https://temp-mail.org/en/option/change/

@o3enzyme.com
@sfamo.com
@trimsj.com
@larjem.com
@yk20.com
@l0real.net
@topikt.com
@99pubblicita.com
@taylorventuresllc.com
@fxprix.com
@loketa.com
@nickrizos.com
@vpslists.com
@dumoac.net
@creazionisa.com
@shinnemo.com

**Comment by techinnov-974** [comment]
Oh sorry I did not see that you already added that ^^

**Comment by FGRibreau** [comment]
Ok, closing then :)
