### ISSUE TITLE
Temporary record

### ISSUE THREAD

**Issue by kslr** [FGRibreau/mailchecker#152]
I will keep recording, submit Pr

**Comment by kslr** [comment]
mailhex.com
idx4.com
rsvhr.com
voltaer.com 
zsero.com
kulmeo.com
xcodes.net 
daabox.com 
moruzza.com 
veanlo.com 
heros3.com 
autowb.com 
3202.com 
mail.libivan.com 
mdu.edu.rs 
meihuajun76.com 
jnpayy.com 
oiizz.com

**Comment by kslr** [comment]
shayzam.net
1766258.com

**Comment by kslr** [comment]
zdfpost.net 
providier.com 
laonanrenj.com

**Comment by FGRibreau** [comment]
great!
I will accept a PR for it :+1: :)

**Comment by kslr** [comment]
lagify.com 
mailox.fun 
khtyler.com

**Comment by kslr** [comment]
I want to write a Laravel SDK to support automatic syncing list.json.

**Comment by kslr** [comment]
@FGRibreau 
Do I need to execute gen.js every time I submit?

**Comment by FGRibreau** [comment]
@kslr please do not, just change list.json and I will do the rest when I create a release :)
