### ISSUE TITLE
Switch to plain text list

### ISSUE THREAD

**Issue by nalgeon** [FGRibreau/mailchecker#169]
Hi Francois-Guillaume!

Have you considered switching from list.json to plain text file (one line — one domain, probably with # or // for commented lines)? This giant array-of-arrays json is getting really hard to deal with.

**Comment by kslr** [comment]
JSON has better flexibility and expansion.
For a huge JSON, by compiling and merging?

**Comment by nalgeon** [comment]
How does json has better flexibility in this case? All we really need is the list of domains. Any additional structure only adds noise. Actually, we don't even need comments in list.json, because there are commits with associated comments.

**Comment by FGRibreau** [comment]
I kind of agree with @nalgeon, a text file might be better. I'm open for a PR however we do have to upgrade all languages template libraries at the same time to make it work :)

**Comment by nalgeon** [comment]
OMG that might be problematic. I'll look into it ツ

**Comment by kslr** [comment]
Ok, but we need to keep json.(Auto generated)
Use a simplified format. Simpler, clearer, and easier for network transmission.
such as gitraw, etc.

**Comment by nalgeon** [comment]
Implemented in #171
