### ISSUE TITLE
Request to remove "mail2world.com" from the list

### ISSUE THREAD

**Issue by naresh291** [FGRibreau/mailchecker#179]
Hello Admin

We are using this open source list for validating disposable email domains during the order creation flow. We received multiple feedbacks on "mail2world.com". This is a legitimate email service and not a disposable email service like mailinator.com.

Is it possible to remove "mail2world.com" from this list?

Thanks for the consideration.

**Comment by FGRibreau** [comment]
Could you please send a PR for that? Thanks
