### ISSUE TITLE
com.ar is listed as blacklisted

### ISSUE THREAD

**Issue by alongat** [FGRibreau/mailchecker#197]
Hi,

in v3.2.30 "com.ar" was added as blacklisted even though it belongs to "companies and individuals resident in Argentina"

Was this on purpose? 

Thanks

**Comment by FGRibreau** [comment]
I hope not, please open a PR to fix this :)

**Comment by alongat** [comment]
done :) https://github.com/FGRibreau/mailchecker/pull/201 
Thanks.

**Comment by FGRibreau** [comment]
Fixed in 3.2.37 :)
