### ISSUE TITLE
Please remove unseen.is from list it does not provide temporary email addresses.

### ISSUE THREAD

**Issue by jspaces** [FGRibreau/mailchecker#265]
I have been using unseen.is email accounts for the last 6 years and paid for it. It is not a temporary address provider. The fact it is on the list is causing me to have issues with websites. Please remove it from the list.
Again that is "unseen.is" which is based in Iceland.
Thanks
JSpaces

**Comment by FGRibreau** [comment]
Please provide a PR with this change so we can merge it back :)
