### ISSUE TITLE
list.json isn’t JSON 

### ISSUE THREAD

**Issue by peterhellberg** [FGRibreau/mailchecker#27]
The [list.json](https://raw.githubusercontent.com/FGRibreau/mailchecker/master/list.json) isn’t JSON since it includes comments. Comments are not part of the JSON format.

**Comment by FGRibreau** [comment]
Yes I know, I prefer it this way, no I won't change it but thanks for the reminder :)

**Comment by Anachron** [comment]
Why use a standard if you don't follow it's rules? :confused:

**Comment by FGRibreau** [comment]
The file should be renamed to [.cjson](https://github.com/kof/node-cjson) instead of .json indeed. It will be, one day :)
