### ISSUE TITLE
gmailnator.com - change of logic required

### ISSUE THREAD

**Issue by michield** [FGRibreau/mailchecker#297]
PR #289 adds the gmailnator.com domain

However, looking at gmailnator.com, the problem is that they create gmail addresses.

So, the logic would need to change. Eg they generate

mfpstmp+kjort@gmail.com

which means that mfpstmp+XXXX@gmail.com needs to be blocked. 

They are using the gmail-+ trick: https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html

**Comment by UmanShahzad** [comment]
@michield It seems more complex than this. Try generating more addresses; they have a variety of different types. I don't know if you could reliably block most of this, but I do notice that most of their usernames that use the 'XXXX+YYYY@gmail.com' format have 'tmp' at the end of the 'XXXX' part, e.g. `pushtmp+YYYY@gmail.com` or your example.

So not sure if this library can do it, but a custom solution could create a heuristic to check for `tmp` at the end and perform some extra checks.

**Comment by UmanShahzad** [comment]
Actually if you use https://www.gmailnator.com/bulk-emails and generate the full list over and over, clean it up by removing all the '+YYYY' parts and all the dots (`.`), you can likely get a pretty big list of their unique gmail addresses.

**Comment by michield** [comment]
Yes, considering they offer a mailinator like service, which allows you to read the mails for a short while, they must have a fixed set of mailboxes set up on Gmail that they pop. Some spidering tool could just fetch them all.

**Comment by Buffele** [comment]
Why don't you just disallow emails that contain "+"? This would fix all of it and also the possibility to mass create accounts with the plus trick.

**Comment by UmanShahzad** [comment]
It's not a bad idea at all for signup.

Some services may already have valid users registered with that format though, so if they do mail-checking in bulk post-signup, this wouldn't work well.

**Comment by FGRibreau** [comment]
Closing because it had no updates.
