### ISSUE TITLE
Python platform enhancement

### ISSUE THREAD

**Issue by joke2k** [FGRibreau/mailchecker#33]
Hi I would like to fork this project to add this function in python but I've some problems:

* the regex for email does not work
* the convention for test module (platform.python.test.py) is not valid in python
* how can we create a package and upload it on pypi? 

thank you

**Comment by FGRibreau** [comment]
Hello @joke2k, maybe you could take a look at #35?

How far, considering #35, are we from releasing a python package?

**Comment by FGRibreau** [comment]
+1
