### ISSUE TITLE
What's the breaking change in 5.0?

### ISSUE THREAD

**Issue by guyellis** [FGRibreau/mailchecker#370]
Thank you for this module!

I (and I'm sure others) would love it if the breaking change(s) for 5.0 was listed in an easy to discover manner in the `CHANGELOG.md` file.

Kudos for at least having a `CHANGELOG.md` file!

**Comment by FGRibreau** [comment]
Yes, from the changelog you will see that #369 was merged, I updated my comment to be more explicit about why a new major version: https://github.com/FGRibreau/mailchecker/pull/369#issuecomment-1205728702 :)
