### ISSUE TITLE
remove lilo.org

### ISSUE THREAD

**Issue by diroots** [FGRibreau/mailchecker#389]
legit users create accounts with lilo.org domain

as they are in the list, when checking disposable mails, they get blocked

they actually migrate to new service : https://mailo.lilo.org/ 

before that, they proposed an address obfuscation service like mozmail

**Comment by FGRibreau** [comment]
Hello :)

Please send a PR for this I will merge it, thanks!

**Comment by diroots** [comment]
PR done @FGRibreau  Many thanks

**Comment by MEmmanuel** [comment]
Hi !
Legit user here.
Thx @diroots to deal with the issue and PR and thx @FGRibreau to maintain.
😄
