### ISSUE TITLE
Add enhancedzoom.com

### ISSUE THREAD

**Issue by hansott** [FGRibreau/mailchecker#392]
Created a user like "lngjr64uew@enhancedzoom.com"

Wanted to create the pull request myself but my browser froze because of the big file (don't have the repo locally), any way we can make that easier?

**Comment by hansott** [comment]
https://temp-inbox.com/

**Comment by FGRibreau** [comment]
Hello @hansott, 

Please [clone git repository locally](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository), do the change, commit the change, push the change and then create a pull-request for it here :) 

https://github.com/FGRibreau/mailchecker/blob/master/CONTRIBUTING.md

**Comment by hansott** [comment]
See #394
