### ISSUE TITLE
24hourfitness.com?

### ISSUE THREAD

**Issue by ctbeiser** [FGRibreau/mailchecker#397]
I was looking through the list to check on data quality, and I noticed that 24hourfitness.com is blocked. It appears to be the actual domain of the gym chain 24HourFitness—is it really supposed to be here?

**Comment by FGRibreau** [comment]
Website is down from here so I suspect it to be a spam domain.

**Comment by ctbeiser** [comment]
When I go to it, I find the following website:
<img width="1566" alt="Screenshot 2023-01-24 at 14 17 00" src="https://user-images.githubusercontent.com/614019/214433605-d68ede1f-72b0-43ee-9b59-1b22cd0bc93f.png">

It's also listed as the actual domain of the gym chain here:
https://en.wikipedia.org/wiki/24_Hour_Fitness
