### ISSUE TITLE
Please remove me from contributors list.

### ISSUE THREAD

**Issue by ryancdotorg** [FGRibreau/mailchecker#404]
I'm not sure when it was added, but I seem to have been added to the contributors list on this package. I am philosophically opposed to the purpose of this package, and am concerned that my inclusion as a "contributor" may be interpreted as a tacit endorsement. Please remove my name, both from the readme and the packages file.

Thanks.

**Comment by FGRibreau** [comment]
I don't see your name ("ryancdotorg") in our auto-generated contributor list in README.md, if it's somewhere be more explicit please :pray: and I will fix it,

**Comment by ryancdotorg** [comment]
https://github.com/FGRibreau/mailchecker/blob/2eacf6a652cbd116a26e8e88ed21113a8c25b372/README.md?plain=1#L347
https://github.com/FGRibreau/mailchecker/blob/2eacf6a652cbd116a26e8e88ed21113a8c25b372/package.json#L98

**Comment by FGRibreau** [comment]
Fixed https://github.com/FGRibreau/mailchecker/commit/cd8831e3410d4d307802937fcefd5aa7956e8598
Not sure it will not come back since the contributor list is fully automated and based on commit author, see https://github.com/FGRibreau/mailchecker/blob/master/package.json#L28
