### ISSUE TITLE
Email domain to remove

### ISSUE THREAD

**Issue by VinnieLendscape** [FGRibreau/mailchecker#406]
Hi there,

Can you please remove @lendscape.com from the throwable domain list? This is our company email address for [www.lendscape.com].

We moved to this domain around 8 months ago and have had email deliverability issues ever since.

Thank you!

**Comment by FGRibreau** [comment]
Please follow https://github.com/FGRibreau/mailchecker/blob/master/CONTRIBUTING.md :)
