### ISSUE TITLE
tfbnw.net is not (really) a disposable domain

### ISSUE THREAD

**Issue by laurentgoudet** [FGRibreau/mailchecker#420]
Cross-posting from https://github.com/disposable/disposable/issues/135, `@tfbnw.net` is part of https://github.com/FGRibreau/mailchecker/blame/master/list.txt, which causes Facebook to report integrations as broken (e.g. `Developer Policy 6.1 - Facebook Login is broken`), as Facebook seems to be using that domain for testing.

It seems to have been introduced in a4124ad90208aa2a2e6163f3cc46052c4d6feebe, coming from https://github.com/nfacha/temporary-email-list, and has been in that later list since the start (https://github.com/nfacha/temporary-email-list/commit/ae968f563ecbe37d6a15e010e7d72ec903acdb12).

Happy to make a PR to remove it but I wanted to create a ticket first as that domain is definitely not used by legit users, but AFAIK Facebook test users have never been able to receive emails in the first place, i.e. not sure if it fits the definition of "disposable" (since they won't pass email verification). However Facebook seems to have been made aware of an issue as they blocked the creation on new test users back in Feb this year, which would suggest they were abused in some way.

Personally I'll be tempted to remove it to prevent policy violations reports from Facebook, which are tricky to process since they don't provide any details, but I don't have a strong opinion about it.

**Comment by FGRibreau** [comment]
Please follow https://github.com/FGRibreau/mailchecker/blob/master/CONTRIBUTING.md
