### ISSUE TITLE
Some other domains are missing

### ISSUE THREAD

**Issue by trisix** [FGRibreau/mailchecker#43]
Hello, 

I found that some other email domains related to "@kmhow.com" are missing from the list:

- @pooae.com
- @foxja.com
- @kloap.com

You can find it on https://10minutemail.net/history.html

Cheers :beer:

**Comment by FGRibreau** [comment]
@trisix will happily accept a PR for this :)

**Comment by trisix** [comment]
#44  

@FGRibreau  Thanks~ :)
