### ISSUE TITLE
Add new disposable

### ISSUE THREAD

**Issue by ghost** [FGRibreau/mailchecker#437]
Provider is https://skiff.com/quick-alias and it's actually subdomains, each user can generate their own subdomain. I tested it, very easy.

The page title of https://skiff.com/quick-alias is "Quick alias burner email address". In the HTML I see

```
<meta name="description" content="Secure and quick-to-create burner email addresses with Skiff!
```
There is a browser plugin https://github.com/irazasyed/email-masker to create one email per website, skiff.com's twitter account promoted it, the github repository is tagged as 'burner-email'

You should add:

- `maskmy.id` because it is there main domain
- `anything.maskmy.id` because it allows you to create disposable addresses with random subdomains
![IMG_1500](https://github.com/7c/fakefilter/assets/153675616/ed76e1cc-0662-4c47-9633-c3ea618e0741)
![IMG_1501](https://github.com/7c/fakefilter/assets/153675616/83576fdc-377f-4ad1-b5d3-3429fc560d04)

**Comment by FGRibreau** [comment]
Thanks a lot!
Please follow https://github.com/FGRibreau/mailchecker/blob/master/CONTRIBUTING.md to open a PR :)

**Comment by Liaddi** [comment]
@FGRibreau created :)

**Comment by Hchchg** [comment]
Also

**
mailbox.zip
sailmail.io
**

They added new domains:
![IMG_1719](https://github.com/FGRibreau/mailchecker/assets/155533164/48430066-7c02-45ef-ae84-3057efa6c5db)

**Comment by byhkl** [comment]
I have added a temporary email address mail.xiuvi.cn to the list and request approval through.
