### ISSUE TITLE
6.0.2 release is not on packagist (PHP package manager)

### ISSUE THREAD

**Issue by lyrixx** [FGRibreau/mailchecker#442]
This tag is not present on packagist: https://packagist.org/packages/fgribreau/mailchecker

**Comment by oprypkhantc** [comment]
@FGRibreau Can you please create a tag for v6.0.2? Seems you made a release but no tag

**Comment by FGRibreau** [comment]
@lyrixx I've finally (had the time to) invited you to github and packagist as a collaborator. You can fix the PHP package now :)

**Comment by lyrixx** [comment]
Actually, the tag was missing on this repository. I add the tag  [v6.0.2](https://github.com/FGRibreau/mailchecker/releases/tag/v6.0.2), and the release is now on [packagist ](https://packagist.org/packages/fgribreau/mailchecker)

Thanks @FGRibreau
