### ISSUE TITLE
All "my.id" and "web.id" are blocked.

### ISSUE THREAD

**Issue by bayuah** [FGRibreau/mailchecker#459]
It seems all domain with suffix `my.id` and `web.id` as flagged as "list.txt" say. Both are domain that for personal use in Indonesia.

I personally use `web.id` for my email domain **NOT** for disposable purpose.  Also for `web.id` need national residential ID for registration, so this is somewhat secure.

Why both there and is this possible to remove both as it will trigger false positive?

Thank you.

**Further reading:** https://en.wikipedia.org/wiki/.id

**Comment by fipo** [comment]
@FGRibreau
https://verifymail.io/domain/web.id => web.id is safe
https://verifymail.io/domain/my.id => my.id is safe

**Comment by FGRibreau** [comment]
Could you please open a PR for that? 

See https://github.com/FGRibreau/mailchecker/blob/master/CONTRIBUTING.md

I will merge it, thanks :)

**Comment by pointmax** [comment]
I have created a pull request for that here: https://github.com/FGRibreau/mailchecker/pull/492

**Comment by lyrixx** [comment]
Done via https://github.com/FGRibreau/mailchecker/pull/492
