### ISSUE TITLE
Russian domains

### ISSUE THREAD

**Issue by egorsmkv** [FGRibreau/mailchecker#51]
This is not temp. domains:

- mail333.com (domain as alias for qip.ru)
- sibmail.com
- mail.by

**Comment by FGRibreau** [comment]
Good question, it seems they were consider like that from by the community. I will wait for "+1" to remove some :)

**Comment by egorsmkv** [comment]
I do not think people come here to vote (especially from Russia or China).

**The problem is that other developers to embed themselves your library immediately to block domains postal services which are not temporary.**

Your like the author of this project, you need to check every domain, but simply copied from open source.

**Comment by FGRibreau** [comment]
Hello @egorsmkv,

mail333.com is blocked by uBlock Origin and google chrome marked it as dangerous.

About sibmail and mail.by I don't know what we should do about them, since no one else asked for them I'm closing this issue for now.
