### ISSUE TITLE
error in sample implementation

### ISSUE THREAD

**Issue by luisj135** [FGRibreau/mailchecker#74]
when trying to run the following code does not work

`
if(!MailChecker.isValid('myemail@yopmail.com')){
  console.error('O RLY !');
}

if(!MailChecker.isValid('myemail.com')){
  console.error('O RLY !');
}
`
evidenced the following error

registro:338 Uncaught ReferenceError: MailChecker is not defined

**Comment by FGRibreau** [comment]
This is because you need to install mailchecker with `npm install mailchecker`

and require it with `var MailChecker = require('mailchecker');`.

We did not specify it because that's how every NodeJS module works :)
