### ISSUE TITLE
list.json uses non-standard syntax - could be formatted also for easier parsing

### ISSUE THREAD

**Issue by xor-gate** [FGRibreau/mailchecker#75]
I tried to implement a Golang platform but got stuck at how the list.json file is formatted. It uses non-standard single-line comments. And it is formatted as an array of arrays with strings. To be more compliant I suggest it should be a array of strings, where every string is on a seperate line. 

I have already drafted a golang library generator script but parsing this is currently a pain. Checking for duplicates is also much easier then (with unix tools) if every domain string is in on a separate file.

What do you think?

**Comment by FGRibreau** [comment]
Hello @xor-gate,

Awesome news!

Let me explain, the list.json format is that way for maintenance purpose so it's easier for human to review changes.

Why don't you use https://github.com/yosuke-furukawa/json5 for the parsing step?
